config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get "/auth/spotify",          as: :spotify_login
  get "/auth/spotify/callback", to: "sessions#create"
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.image = auth_info["info"]["image"]
      new_user.token = auth_info["credentials"]["token"]
      new_user.refresh_token = auth_info["credentials"]["refresh_token"]
      new_user.token_expiry = Time.at(auth_info["credentials"]["expires_at"].to_i)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(uid: session[:uid]) if session[:uid]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:uid] = user.uid
    else
      flash[:danger] = "There was a problem signing in."
    end
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpotifyMigrator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "react" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <%= render partial: "shared/navbar" %>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
  <% end %>
  <%= yield %>
  <%= react_component "Thing" %>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Spotify Migrator", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.uid %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>Playlists</li>
              <li>Logout</li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login with Spotify", spotify_login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>